# keys = ["game_id",
#   "team_id",
#   "HoA",
#   "won",
#   "settled_in",
#   "head_coach",
#   "goals",
#   "shots",
#   "hits",
#   "pim",
#   "powerPlayOpportunities",
#   "powerPlayGoals",
#   "faceOffWinPercentage",
#   "giveaways",
#   "takeaways"]
